### ISSUE TITLE
Latest webui and LTM error on generate with unexpected keyword 'end_of_turn'

### ISSUE THREAD

**Issue by maociao** [wawawario2/long_term_memory#14] opened 2023-04-08 02:39 UTC
Latest webui pull and latest LTM pull errors on generate..

Full Traceback (trimmed the folder paths for readability):

Traceback (most recent call last):
  File "\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "\text-generation-webui\modules\chat.py", line 206, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, generate_state, name1, name2, context, mode, end_of_turn):
  File "\text-generation-webui\modules\chat.py", line 134, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'

**Comment by Keysmash2b** [comment] 2023-04-08 03:50
Can also verify exact same issues in the same lines:
Traceback (most recent call last):
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "C:\Users\Julien\Ooba\text-generation-webui\modules\chat.py", line 204, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, generate_state, name1, name2, context, mode, end_of_turn):
  File "C:\Users\Julien\Ooba\text-generation-webui\modules\chat.py", line 131, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'
Traceback (most recent call last):
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "C:\Users\Julien\Ooba\text-generation-webui\modules\chat.py", line 204, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, generate_state, name1, name2, context, mode, end_of_turn):
  File "C:\Users\Julien\Ooba\text-generation-webui\modules\chat.py", line 131, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'
Traceback (most recent call last):
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Julien\Ooba\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "C:\Users\Julien\Ooba\text-generation-webui\modules\chat.py", line 204, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, generate_state, name1, name2, context, mode, end_of_turn):
  File "C:\Users\Julien\Ooba\text-generation-webui\modules\chat.py", line 131, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'

**Comment by Keysmash2b** [comment] 2023-04-08 03:51
Can also verify exact same lines having issues.

**Comment by oobabooga** [comment] 2023-04-08 04:12
This is the fix

```diff
--- a/script.py
+++ b/script.py
@@ -233,7 +233,7 @@ def custom_generate_chat_prompt(
     name2,
     context,
     chat_prompt_size,
-    impersonate=False,
+    **kwargs
 ):
     """Main hook that allows us to fetch and store memories from/to LTM."""
     print("=" * 60)
@@ -252,6 +252,7 @@ def custom_generate_chat_prompt(
         augmented_context = _build_augmented_context(memory_context, context)
     debug_texts["current_context_block"] = augmented_context
 
+    kwargs['also_return_rows'] = True
     (prompt, prompt_rows) = generate_chat_prompt(
         user_input,
         max_new_tokens,
@@ -259,8 +260,7 @@ def custom_generate_chat_prompt(
         name2,
         augmented_context,
         chat_prompt_size,
-        impersonate,
-        also_return_rows=True,
+        **kwargs
     )
 
     # === Clean and add new messages to LTM ===

```

**Comment by bubbabug** [comment] 2023-04-08 18:00
> This is the fix
> 
> ```diff
> --- a/script.py
> +++ b/script.py
> @@ -233,7 +233,7 @@ def custom_generate_chat_prompt(
>      name2,
>      context,
>      chat_prompt_size,
> -    impersonate=False,
> +    **kwargs
>  ):
>      """Main hook that allows us to fetch and store memories from/to LTM."""
>      print("=" * 60)
> @@ -252,6 +252,7 @@ def custom_generate_chat_prompt(
>          augmented_context = _build_augmented_context(memory_context, context)
>      debug_texts["current_context_block"] = augmented_context
>  
> +    kwargs['also_return_rows'] = True
>      (prompt, prompt_rows) = generate_chat_prompt(
>          user_input,
>          max_new_tokens,
> @@ -259,8 +260,7 @@ def custom_generate_chat_prompt(
>          name2,
>          augmented_context,
>          chat_prompt_size,
> -        impersonate,
> -        also_return_rows=True,
> +        **kwargs
>      )
>  
>      # === Clean and add new messages to LTM ===
> ```

I'm sorry but I've been trying to get this working for a little while now. I know that the appropriate place is in the long_term_memory script.py, but I cannot figure out how to make this work. If I copy and paste it over the existing code it throws syntax errors. Could you please tell me how exactly to get this working?

**Comment by Ph0rk0z** [comment] 2023-04-08 18:06
it's a patch, here is the whole thing https://pastebin.com/7hF375M4

**Comment by bubbabug** [comment] 2023-04-08 18:21
> it's a patch, here is the whole thing https://pastebin.com/7hF375M4

thanks so much!

**Comment by wawawario2** [comment] 2023-04-08 21:57
Thanks for reporting this all, it should be fixed now.

**Comment by digiwombat** [comment] 2023-04-09 03:32
Confirmed fixed for me on Windows native, presumably fine everywhere since it's just Python changes.

**Closed** 2023-04-13 13:21 UTC
